ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP1()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_39 = (MDL_CW*MDL_EE*MDL_COMPLEXI*MDL_SA)/(2.000000D+00*MDL_SW)
      GC_48 = -(MDL_CA*MDL_EE*MDL_ETA*MDL_COMPLEXI)/(2.000000D+00
     $ *MDL_CW)-(MDL_EE*MDL_COMPLEXI*MDL_SA*MDL_SW)/(2.000000D+00
     $ *MDL_CW)
      GC_61 = (MDL_CA__EXP__2*MDL_EE__EXP__2*MDL_ETA__EXP__2
     $ *MDL_COMPLEXI*MDL_SH*MDL_V)/(2.000000D+00*MDL_CW__EXP__2)
     $ +MDL_EE__EXP__2*MDL_COMPLEXI*MDL_SA__EXP__2*MDL_SH*MDL_V
     $ +(MDL_CW__EXP__2*MDL_EE__EXP__2*MDL_COMPLEXI*MDL_SA__EXP__2
     $ *MDL_SH*MDL_V)/(2.000000D+00*MDL_SW__EXP__2)+(MDL_CA
     $ *MDL_EE__EXP__2*MDL_ETA*MDL_COMPLEXI*MDL_SA*MDL_SH*MDL_V)
     $ /MDL_SW+(MDL_CA*MDL_EE__EXP__2*MDL_ETA*MDL_COMPLEXI*MDL_SA
     $ *MDL_SH*MDL_SW*MDL_V)/MDL_CW__EXP__2+(MDL_EE__EXP__2
     $ *MDL_COMPLEXI*MDL_SA__EXP__2*MDL_SH*MDL_SW__EXP__2*MDL_V)
     $ /(2.000000D+00*MDL_CW__EXP__2)+(2.000000D+00*MDL_CA__EXP__2
     $ *MDL_CH*MDL_ETA__EXP__2*MDL_COMPLEXI*MDL_GX__EXP__2*MDL_XI)
     $ /MDL_CHI__EXP__2
      GC_64 = (MDL_CA__EXP__2*MDL_CH*MDL_EE__EXP__2*MDL_ETA__EXP__2
     $ *MDL_COMPLEXI*MDL_V)/(2.000000D+00*MDL_CW__EXP__2)+MDL_CH
     $ *MDL_EE__EXP__2*MDL_COMPLEXI*MDL_SA__EXP__2*MDL_V+(MDL_CH
     $ *MDL_CW__EXP__2*MDL_EE__EXP__2*MDL_COMPLEXI*MDL_SA__EXP__2
     $ *MDL_V)/(2.000000D+00*MDL_SW__EXP__2)+(MDL_CA*MDL_CH
     $ *MDL_EE__EXP__2*MDL_ETA*MDL_COMPLEXI*MDL_SA*MDL_V)/MDL_SW
     $ +(MDL_CA*MDL_CH*MDL_EE__EXP__2*MDL_ETA*MDL_COMPLEXI*MDL_SA
     $ *MDL_SW*MDL_V)/MDL_CW__EXP__2+(MDL_CH*MDL_EE__EXP__2
     $ *MDL_COMPLEXI*MDL_SA__EXP__2*MDL_SW__EXP__2*MDL_V)/(2.000000D
     $ +00*MDL_CW__EXP__2)-(2.000000D+00*MDL_CA__EXP__2
     $ *MDL_ETA__EXP__2*MDL_COMPLEXI*MDL_GX__EXP__2*MDL_SH*MDL_XI)
     $ /MDL_CHI__EXP__2
      GC_75 = -((MDL_CH*MDL_COMPLEXI*MDL_YE)/MDL_SQRT__2)
      GC_76 = -((MDL_COMPLEXI*MDL_SH*MDL_YE)/MDL_SQRT__2)
      END
