ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of HAHM_darkphoton_iDM_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_39 = ', GC_39
      WRITE(*,2) 'GC_48 = ', GC_48
      WRITE(*,2) 'GC_61 = ', GC_61
      WRITE(*,2) 'GC_64 = ', GC_64
      WRITE(*,2) 'GC_75 = ', GC_75
      WRITE(*,2) 'GC_76 = ', GC_76
